
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: copy roboshop configuration
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: clean old content
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: create directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and extract application content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name : restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true

- name: Create Nginx Prometheus Exporter Directory
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory

- name: Download Nginx Prometheus Exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes

- name: copy nginx prometheus  exporter
  ansible.builtin.copy:
    src: nginx-exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: restart nginx prometheus exporter
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted
    enabled: true