    - name: install golang
      ansible.builtin.yum:
        name: golang
        state: installed

    - name: app prerequistie
      ansible.builtin.import_tasks: appreq.yml

    - name: install the dependencies
      ansible.builtin.shell: go mod init dispatch
      args:
        chdir: /app

    - name: install the dependencies
      ansible.builtin.shell: go get
      args:
        chdir: /app

    - name: install the dependencies
      ansible.builtin.shell: go build
      args:
        chdir: /app

    - name: app prerequistie
      ansible.builtin.import_tasks: systemd.yml
