- name: systemd setup
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: start {{ component }} service
  ansible.builtin.systemd:
    name: "{{  component }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: setup rsyslog conf file
  ansible.builtin.template:
    src: "rsyslog.conf"
    dest: /etc/rsyslog.d/roboshop.conf

- name: start rsyslog service
  ansible.builtin.systemd:
    name: "rsyslog"
    state: restarted


